-- =============================================
-- SEED DATA SCRIPT FOR THE ENIGMA ENGINE
-- Run this script to populate the database with demo data.
-- Usage: mysql -u root -p enigma_db < backend/seed_data.sql
-- =============================================

USE enigma_engine_db;

-- 1. Clean up existing data (Optional - be careful!)
-- TRUNCATE TABLE Session_Hints_Used;
-- DELETE FROM Game_Sessions WHERE sessionID > 0;
-- DELETE FROM Payments WHERE paymentID > 0;
-- DELETE FROM Invoices WHERE invoiceID > 0;
-- DELETE FROM Bookings WHERE bookingID > 0;
-- DELETE FROM Puzzle_Hints WHERE puzzleID > 0;
-- DELETE FROM Digital_Puzzles WHERE puzzleID > 0;
-- DELETE FROM Physical_Puzzles WHERE puzzleID > 0;
-- DELETE FROM Puzzles WHERE puzzleID > 0;
-- DELETE FROM Rooms WHERE roomID > 0;
-- DELETE FROM Staff WHERE userID > 0;
-- DELETE FROM Customers WHERE userID > 0;
-- DELETE FROM Users WHERE userID > 0;

-- Error Code: 1175. You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.  To disable safe mode, toggle the option in Preferences -> SQL Editor and reconnect.


-- 2. Insert Users (Passwords are 'password123' hashed with pbkdf2:sha256)
-- Note: In a real scenario, use the application to register to get correct hashes.
-- For this script, we will insert raw data. 
-- The hash below is for 'password123' generated by werkzeug.security.generate_password_hash
SET @common_hash = 'scrypt:32768:8:1$l4JqW0X8$1b1d9f8a6c8e5b2a4d3e9f0g1h2i3j4k5l6m7n8o9p0q1r2s3t4u5v6w7x8y9z'; 
-- REPLACE THE ABOVE HASH with a valid one from your local DB if needed, or register one user and copy their hash.
-- For the purpose of this script, let's assume the application handles hashing or we use a known hash.
-- Actually, it's safer to use the Stored Procedure for Users to ensure logic holds, but SPs might not be easily scriptable for bulk without a loop or just direct inserts.
-- Let's use direct inserts for speed, assuming we know a valid hash.
-- If you don't have a valid hash, you might need to register one user via UI and copy it here.
-- Let's use a placeholder hash that works if you registered a user with 'password123'.
-- If you haven't, these users won't be able to login unless you update the hash.
-- HASH FOR 'password123' (Example):
SET @pw_hash = 'scrypt:32768:8:1$iOEpAjF5q6dlaAZr$e34d338925f64631ee03cc7f2b77818563cf17b00216d077e13c077f4f3b6bdfa94236ad59472bf0ab9d3614400ca3c89d276ceca19de221d9abdf35d4890c15'; 

-- Admin User
INSERT INTO Users (email, hashedPassword, firstName, lastName, phone) VALUES 
('admin@enigma.com', @pw_hash, 'Alice', 'Admin', '555-0101');
SET @admin_id = LAST_INSERT_ID();
INSERT INTO Staff (userID, role, hireDate, payRate) VALUES (@admin_id, 'Admin', '2023-01-15', 35.00);

-- Game Master User
INSERT INTO Users (email, hashedPassword, firstName, lastName, phone) VALUES 
('gm@enigma.com', @pw_hash, 'Gary', 'Master', '555-0102');
SET @gm_id = LAST_INSERT_ID();
INSERT INTO Staff (userID, role, hireDate, payRate) VALUES (@gm_id, 'GameMaster', '2023-03-10', 20.00);

-- Customer 1
INSERT INTO Users (email, hashedPassword, firstName, lastName, phone) VALUES 
('john@doe.com', @pw_hash, 'John', 'Doe', '555-0103');
SET @cust1_id = LAST_INSERT_ID();
INSERT INTO Customers (userID, dateOfBirth, loyaltyPoints) VALUES (@cust1_id, '1990-05-20', 50);

-- Customer 2
INSERT INTO Users (email, hashedPassword, firstName, lastName, phone) VALUES 
('jane@smith.com', @pw_hash, 'Jane', 'Smith', '555-0104');
SET @cust2_id = LAST_INSERT_ID();
INSERT INTO Customers (userID, dateOfBirth, loyaltyPoints) VALUES (@cust2_id, '1995-08-15', 120);

-- 3. Insert Rooms
INSERT INTO Rooms (name, description, difficultyLevel, maxPlayers, durationMinutes, pricePerPerson) VALUES 
('The Haunted Mansion', 'Explore the spooky corridors of the Blackwood Manor. Find the hidden artifact before the ghosts catch you!', 7, 6, 60, 30.00),
('Cyberpunk Heist', 'In the year 2077, you must infiltrate the Arasaka tower and steal the prototype chip. High-tech puzzles await.', 9, 4, 75, 35.00),
('Pirate\'s Cove', 'Escape from the brig of the Black Pearl and find the captain\'s treasure map.', 4, 8, 45, 25.00);

SET @room1_id = (SELECT roomID FROM Rooms WHERE name = 'The Haunted Mansion');
SET @room2_id = (SELECT roomID FROM Rooms WHERE name = 'Cyberpunk Heist');
SET @room3_id = (SELECT roomID FROM Rooms WHERE name = 'Pirate\'s Cove');

-- 3.5. Insert Room Availability schedules
INSERT INTO Room_Availability (roomID, dayOfWeek, openTime, closeTime) VALUES
-- Haunted Mansion - Open all week
(@room1_id, 'Monday', '10:00:00', '22:00:00'),
(@room1_id, 'Tuesday', '10:00:00', '22:00:00'),
(@room1_id, 'Wednesday', '10:00:00', '22:00:00'),
(@room1_id, 'Thursday', '10:00:00', '22:00:00'),
(@room1_id, 'Friday', '10:00:00', '23:00:00'),
(@room1_id, 'Saturday', '09:00:00', '23:00:00'),
(@room1_id, 'Sunday', '09:00:00', '22:00:00'),

-- Cyberpunk Heist - Limited weekday hours
(@room2_id, 'Wednesday', '14:00:00', '22:00:00'),
(@room2_id, 'Thursday', '14:00:00', '22:00:00'),
(@room2_id, 'Friday', '14:00:00', '23:00:00'),
(@room2_id, 'Saturday', '10:00:00', '23:00:00'),
(@room2_id, 'Sunday', '10:00:00', '22:00:00'),

-- Pirate's Cove - Weekend and evening slots only
(@room3_id, 'Friday', '17:00:00', '23:00:00'),
(@room3_id, 'Saturday', '09:00:00', '23:00:00'),
(@room3_id, 'Sunday', '09:00:00', '22:00:00');

-- 4. Insert Puzzles
-- Haunted Mansion Puzzles
INSERT INTO Puzzles (roomID, name, description, puzzleType) VALUES 
(@room1_id, 'Ghostly Piano', 'Play the correct melody to open the secret door.', 'Physical'),
(@room1_id, 'Portrait Puzzle', 'Arrange the family portraits in chronological order.', 'Physical');

-- Cyberpunk Heist Puzzles
INSERT INTO Puzzles (roomID, name, description, puzzleType) VALUES 
(@room2_id, 'Firewall Breach', 'Hack the terminal by solving the binary sequence.', 'Digital'),
(@room2_id, 'Laser Grid', 'Navigate the laser maze without tripping the alarm.', 'Physical');

-- 4.5. Insert Puzzle Hints with sequence numbers
-- Haunted Mansion - Ghostly Piano hints
INSERT INTO Puzzle_Hints (puzzleID, hintSequence, hintText, timeToTriggerSeconds) VALUES
((SELECT puzzleID FROM Puzzles WHERE name = 'Ghostly Piano'), 1, 'Look at the sheet music on the piano stand.', 300),
((SELECT puzzleID FROM Puzzles WHERE name = 'Ghostly Piano'), 2, 'The notes spell out a word when read backwards.', 600),
((SELECT puzzleID FROM Puzzles WHERE name = 'Ghostly Piano'), 3, 'Play only the black keys in the highlighted pattern.', 900);

-- Haunted Mansion - Portrait Puzzle hints
INSERT INTO Puzzle_Hints (puzzleID, hintSequence, hintText, timeToTriggerSeconds) VALUES
((SELECT puzzleID FROM Puzzles WHERE name = 'Portrait Puzzle'), 1, 'Check the dates on the portraits carefully.', 300),
((SELECT puzzleID FROM Puzzles WHERE name = 'Portrait Puzzle'), 2, 'Arrange them from oldest to newest, left to right.', 600);

-- Cyberpunk Heist - Firewall Breach hints
INSERT INTO Puzzle_Hints (puzzleID, hintSequence, hintText, timeToTriggerSeconds) VALUES
((SELECT puzzleID FROM Puzzles WHERE name = 'Firewall Breach'), 1, 'Binary sequences can be converted to letters.', 240),
((SELECT puzzleID FROM Puzzles WHERE name = 'Firewall Breach'), 2, 'The ASCII table is your friend.', 480),
((SELECT puzzleID FROM Puzzles WHERE name = 'Firewall Breach'), 3, 'The password is a 4-letter word.', 720);

-- Cyberpunk Heist - Laser Grid hints
INSERT INTO Puzzle_Hints (puzzleID, hintSequence, hintText, timeToTriggerSeconds) VALUES
((SELECT puzzleID FROM Puzzles WHERE name = 'Laser Grid'), 1, 'Use the mirrors to redirect the beams.', 300),
((SELECT puzzleID FROM Puzzles WHERE name = 'Laser Grid'), 2, 'The safe path follows the floor tiles lighting pattern.', 600);

-- 5. Insert Bookings & Invoices (Past & Future)

-- Booking 1: Past, Completed, Paid (John Doe)
INSERT INTO Bookings (customerID, roomID, scheduledTime, numPlayers, status) VALUES 
(@cust1_id, @room1_id, DATE_SUB(NOW(), INTERVAL 5 DAY), 4, 'Completed');
SET @book1_id = LAST_INSERT_ID();
INSERT INTO Invoices (bookingID, amountDue, status, dateIssued) VALUES 
(@book1_id, 120.00, 'Paid', DATE_SUB(NOW(), INTERVAL 6 DAY));
SET @inv1_id = LAST_INSERT_ID();
INSERT INTO Payments (invoiceID, amountPaid, paymentMethod, transactionTimestamp) VALUES 
(@inv1_id, 120.00, 'Credit Card', DATE_SUB(NOW(), INTERVAL 5 DAY));

-- Booking 2: Past, Completed, Paid (Jane Smith)
INSERT INTO Bookings (customerID, roomID, scheduledTime, numPlayers, status) VALUES 
(@cust2_id, @room2_id, DATE_SUB(NOW(), INTERVAL 2 DAY), 3, 'Completed');
SET @book2_id = LAST_INSERT_ID();
INSERT INTO Invoices (bookingID, amountDue, status, dateIssued) VALUES 
(@book2_id, 105.00, 'Paid', DATE_SUB(NOW(), INTERVAL 3 DAY));
SET @inv2_id = LAST_INSERT_ID();
INSERT INTO Payments (invoiceID, amountPaid, paymentMethod, transactionTimestamp) VALUES 
(@inv2_id, 105.00, 'PayPal', DATE_SUB(NOW(), INTERVAL 2 DAY));

-- Booking 3: Future, Confirmed, Pending (John Doe)
INSERT INTO Bookings (customerID, roomID, scheduledTime, numPlayers, status) VALUES 
(@cust1_id, @room3_id, DATE_ADD(NOW(), INTERVAL 2 DAY), 5, 'Confirmed');
SET @book3_id = LAST_INSERT_ID();
INSERT INTO Invoices (bookingID, amountDue, status, dateIssued) VALUES 
(@book3_id, 125.00, 'Pending', NOW());

-- Booking 4: Future, Confirmed, Paid (Jane Smith)
INSERT INTO Bookings (customerID, roomID, scheduledTime, numPlayers, status) VALUES 
(@cust2_id, @room1_id, DATE_ADD(NOW(), INTERVAL 5 HOUR), 2, 'Confirmed');
SET @book4_id = LAST_INSERT_ID();
INSERT INTO Invoices (bookingID, amountDue, status, dateIssued) VALUES 
(@book4_id, 60.00, 'Paid', NOW());
SET @inv4_id = LAST_INSERT_ID();
INSERT INTO Payments (invoiceID, amountPaid, paymentMethod, transactionTimestamp) VALUES 
(@inv4_id, 60.00, 'Credit Card', NOW());

-- 6. Insert Game Sessions (For Past Bookings)

-- Session for Booking 1 (Success)
INSERT INTO Game_Sessions (bookingID, gameMasterID, startTime, endTime, success) VALUES 
(@book1_id, @gm_id, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_ADD(DATE_SUB(NOW(), INTERVAL 5 DAY), INTERVAL 55 MINUTE), TRUE);

-- Session for Booking 2 (Failure)
INSERT INTO Game_Sessions (bookingID, gameMasterID, startTime, endTime, success) VALUES 
(@book2_id, @gm_id, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_ADD(DATE_SUB(NOW(), INTERVAL 2 DAY), INTERVAL 75 MINUTE), FALSE);

-- 7. Insert Reviews (If table exists)
INSERT INTO Reviews (bookingID, rating, commentText) VALUES 
(@book1_id, 5, 'Amazing experience! The actors were great.'),
(@book2_id, 4, 'Very hard puzzles, but fun atmosphere.');

SELECT 'Seed data inserted successfully!' AS Status;
